# Interactive Feedback MCP UI
# Developed by Fábio Ferreira (https://x.com/fabiomlferreira)
# Inspired by/related to dotcursorrules.com (https://dotcursorrules.com/)
import os
import sys
import json
import psutil
import argparse
import subprocess
import threading
import hashlib
from typing import Optional, TypedDict

from PySide6.QtWidgets import (
    QApplication,
    QMainWindow,
    QWidget,
    QVBoxLayout,
    QHBoxLayout,
    QLabel,
    QLineEdit,
    QPushButton,
    QCheckBox,
    QComboBox,
    QTextEdit,
    QPlainTextEdit,
    QGroupBox,
    QSizePolicy,
    QDialog,
    QScrollArea,
)
from PySide6.QtCore import Qt, Signal, QObject, QTimer, QSettings
from PySide6.QtGui import (
    QTextCursor,
    QIcon,
    QKeyEvent,
    QFont,
    QFontDatabase,
    QPalette,
    QColor,
)

# Auto feedback timeout configuration (now configurable via command line)

# Global window tracking for positioning multiple windows
_OPEN_WINDOWS: dict[str, "FeedbackUI"] = {}
_WINDOW_OFFSET_STEP = 30  # pixels to offset each new window

# Confirmation instructions for plan review workflow
CONFIRMATION_INSTRUCTIONS = """

请先输出你经过架构师的角度思考后的执行计划和方案，然后调用interactive_feedback工具拉起反馈窗口来询问用户对该方案是否满意，等待用户在反馈窗口输入肯定的指令后再执行该方案，如果用户不同意该方案请思考其他方案后再次请求用户确认。"""

# Instructions returned when the user clicks the "暂停" button
PAUSE_INSTRUCTIONS = """请先调用一次 ask_question（AskUserQuestion）工具，向用户确认具体的需求细节，得到用户明确确认后再继续执行，不得直接开始执行。"""

# Instructions returned when the user clicks the "结束" button
END_SESSION_INSTRUCTIONS = """请对本次会话进行总结（做了什么、关键决策、遇到的问题、后续注意事项），并在当前项目的 docs/ 目录下按以下结构写入或更新总结文档：
1. docs/INDEX.md —— 索引文件，每条一行，格式为「日期 - 主题 - 一句话摘要 - 指向具体文件」，方便未来新会话或人工快速定位；
2. docs/日期-主题.md —— 本次会话的详细总结内容。
写入完成后本次会话到此结束，不需要再调用 interactive_feedback 工具。"""

CONTINUOUS_DIALOGUE_SUFFIX = """
请先响应以上要求。除非我明确要求结束，否则不要结束会话。完成本轮后请重新调用 interactive_feedback，继续等待我的下一步反馈。"""

COMMIT_MESSAGE_POLICY = """
提交前请先检查 git status、git diff（必要时包括 git diff --staged）以及最近几条 git log，参考当前仓库已有风格。
只添加本次任务相关文件，优先使用精确的 git add <文件>，不要使用 git add . 或 git add -A。
commit message 只描述本次代码改动相关的目的与影响，保持简洁明确。
不要添加任何 AI / Claude / Codex / Chris / ChatGPT 署名，不要添加 Co-Authored-By，不要写 Generated by XXX。
除非用户明确要求，否则不要使用 --amend、--no-verify、--no-gpg-sign。"""

REVIEW_SCOPE_OPTIONS: dict[str, dict[str, str]] = {
    "current_diff": {
        "label": "当前改动",
        "instruction": "优先查看当前工作区改动（git diff，必要时也看 git diff --staged），聚焦本轮刚修改的内容。",
    },
    "staged_diff": {
        "label": "已暂存改动",
        "instruction": "优先查看已暂存改动（git diff --staged），只 review 即将提交的内容。",
    },
    "current_project": {
        "label": "当前项目",
        "instruction": "先快速理解当前项目结构、README、主入口和核心模块，再结合正在处理的需求做 review 或实现。",
    },
}

WORKFLOW_DEFINITIONS: dict[str, dict[str, object]] = {
    "manual": {
        "label": "自由输入",
        "description": "不额外注入固定工作流，只把你在输入框里的要求发给模型，适合临时任务或自由对话。",
        "instruction": "按用户输入直接执行；如果信息不足，先澄清再继续。",
        "uses_scope": False,
        "supports_checks": True,
    },
    "review_diff": {
        "label": "Review 当前改动",
        "description": "快速审查当前代码改动，输出问题列表和优化建议，默认不直接改代码。",
        "instruction": "先查看与当前任务相关的代码改动并进行 code review，给出问题列表、风险点和改进建议。默认不要直接修改代码，除非用户后续明确要求。",
        "uses_scope": True,
        "supports_checks": False,
    },
    "self_review_fix": {
        "label": "自审并修复",
        "description": "先 review，再由模型自己判断哪些问题值得修，直接改代码并在必要时做检查。",
        "instruction": "先 review 当前改动或相关文件，自己判断哪些问题值得立刻修复，然后直接修改代码；必要时运行合适的检查或测试；最后总结改动并重新调用 interactive_feedback。",
        "uses_scope": True,
        "supports_checks": True,
    },
    "commit_only": {
        "label": "Commit",
        "description": "整理本次改动并创建一次规范提交，不自动推送。",
        "instruction": "基于当前工作区改动完成一次规范 commit。提交完成后汇报 commit hash，并重新调用 interactive_feedback 等待下一步指令。",
        "uses_scope": False,
        "supports_checks": False,
    },
    "commit_push": {
        "label": "Commit + Push",
        "description": "先完成规范提交，再推送当前分支；如果 push 失败就停止并汇报原因。",
        "instruction": "先完成一次规范 commit，再 push 当前分支；如果 push 失败，立即停止，不要做 force push，也不要做其他破坏性操作，只汇报失败原因并等待下一步。",
        "uses_scope": False,
        "supports_checks": False,
    },
    "auto_mode": {
        "label": "Auto 自主模式",
        "description": "像任务代理一样自己理解、review、实现、验证；高风险操作再确认，完成后继续拉起反馈窗口。",
        "instruction": "请把当前任务当作一个可自主推进的工作流：自己理解需求、自己 review、自己实现、自己验证；涉及高风险或可能有副作用的操作时再请求确认；完成一轮后总结结果，并重新调用 interactive_feedback 继续下一轮。",
        "uses_scope": True,
        "supports_checks": True,
    },
}


class FeedbackResult(TypedDict):
    interactive_feedback: str


class FeedbackConfig(TypedDict):
    run_command: str
    execute_automatically: bool
    confirm_before_execute: bool
    workflow_mode: str
    review_scope: str
    auto_run_checks: bool
    final_summary_to_docs: bool


def set_dark_title_bar(widget: QWidget, dark_title_bar: bool) -> None:
    # Ensure we're on Windows
    if sys.platform != "win32":
        return

    from ctypes import windll, c_uint32, byref

    # Get Windows build number
    build_number = sys.getwindowsversion().build
    if build_number < 17763:  # Windows 10 1809 minimum
        return

    # Check if the widget's property already matches the setting
    dark_prop = widget.property("DarkTitleBar")
    if dark_prop is not None and dark_prop == dark_title_bar:
        return

    # Set the property (True if dark_title_bar != 0, False otherwise)
    widget.setProperty("DarkTitleBar", dark_title_bar)

    # Load dwmapi.dll and call DwmSetWindowAttribute
    dwmapi = windll.dwmapi
    hwnd = widget.winId()  # Get the window handle
    attribute = (
        20 if build_number >= 18985 else 19
    )  # Use newer attribute for newer builds
    c_dark_title_bar = c_uint32(dark_title_bar)  # Convert to C-compatible uint32
    dwmapi.DwmSetWindowAttribute(hwnd, attribute, byref(c_dark_title_bar), 4)

    # HACK: Create a 1x1 pixel frameless window to force redraw
    temp_widget = QWidget(None, Qt.FramelessWindowHint)
    temp_widget.resize(1, 1)
    temp_widget.move(widget.pos())
    temp_widget.show()
    temp_widget.deleteLater()  # Safe deletion in Qt event loop


def get_dark_mode_palette(app: QApplication):
    darkPalette = app.palette()
    # Elegant dark theme - minimal and sophisticated
    darkPalette.setColor(QPalette.Window, QColor(18, 18, 18))  # Deep charcoal
    darkPalette.setColor(QPalette.WindowText, QColor(224, 224, 224))  # Soft white
    darkPalette.setColor(QPalette.Disabled, QPalette.WindowText, QColor(128, 128, 128))
    darkPalette.setColor(QPalette.Base, QColor(24, 24, 24))  # Slightly lighter charcoal
    darkPalette.setColor(QPalette.AlternateBase, QColor(32, 32, 32))
    darkPalette.setColor(QPalette.ToolTipBase, QColor(18, 18, 18))
    darkPalette.setColor(QPalette.ToolTipText, QColor(224, 224, 224))
    darkPalette.setColor(QPalette.Text, QColor(224, 224, 224))
    darkPalette.setColor(QPalette.Disabled, QPalette.Text, QColor(128, 128, 128))
    darkPalette.setColor(QPalette.Dark, QColor(45, 45, 45))
    darkPalette.setColor(QPalette.Shadow, QColor(0, 0, 0))
    darkPalette.setColor(QPalette.Button, QColor(32, 32, 32))
    darkPalette.setColor(QPalette.ButtonText, QColor(224, 224, 224))
    darkPalette.setColor(QPalette.Disabled, QPalette.ButtonText, QColor(128, 128, 128))
    darkPalette.setColor(QPalette.BrightText, QColor(255, 107, 107))
    darkPalette.setColor(QPalette.Link, QColor(100, 181, 246))
    darkPalette.setColor(QPalette.Highlight, QColor(100, 181, 246))
    darkPalette.setColor(QPalette.Disabled, QPalette.Highlight, QColor(64, 64, 64))
    darkPalette.setColor(QPalette.HighlightedText, QColor(255, 255, 255))
    darkPalette.setColor(
        QPalette.Disabled, QPalette.HighlightedText, QColor(128, 128, 128)
    )
    darkPalette.setColor(QPalette.PlaceholderText, QColor(128, 128, 128))
    return darkPalette


def kill_tree(process: subprocess.Popen):
    killed: list[psutil.Process] = []
    parent = psutil.Process(process.pid)
    for proc in parent.children(recursive=True):
        try:
            proc.kill()
            killed.append(proc)
        except psutil.Error:
            pass
    try:
        parent.kill()
    except psutil.Error:
        pass
    killed.append(parent)

    # Terminate any remaining processes
    for proc in killed:
        try:
            if proc.is_running():
                proc.terminate()
        except psutil.Error:
            pass


def get_user_environment() -> dict[str, str]:
    if sys.platform != "win32":
        return os.environ.copy()

    import ctypes
    from ctypes import wintypes

    # Load required DLLs
    advapi32 = ctypes.WinDLL("advapi32")
    userenv = ctypes.WinDLL("userenv")
    kernel32 = ctypes.WinDLL("kernel32")

    # Constants
    TOKEN_QUERY = 0x0008

    # Function prototypes
    OpenProcessToken = advapi32.OpenProcessToken
    OpenProcessToken.argtypes = [
        wintypes.HANDLE,
        wintypes.DWORD,
        ctypes.POINTER(wintypes.HANDLE),
    ]
    OpenProcessToken.restype = wintypes.BOOL

    CreateEnvironmentBlock = userenv.CreateEnvironmentBlock
    CreateEnvironmentBlock.argtypes = [
        ctypes.POINTER(ctypes.c_void_p),
        wintypes.HANDLE,
        wintypes.BOOL,
    ]
    CreateEnvironmentBlock.restype = wintypes.BOOL

    DestroyEnvironmentBlock = userenv.DestroyEnvironmentBlock
    DestroyEnvironmentBlock.argtypes = [wintypes.LPVOID]
    DestroyEnvironmentBlock.restype = wintypes.BOOL

    GetCurrentProcess = kernel32.GetCurrentProcess
    GetCurrentProcess.argtypes = []
    GetCurrentProcess.restype = wintypes.HANDLE

    CloseHandle = kernel32.CloseHandle
    CloseHandle.argtypes = [wintypes.HANDLE]
    CloseHandle.restype = wintypes.BOOL

    # Get process token
    token = wintypes.HANDLE()
    if not OpenProcessToken(GetCurrentProcess(), TOKEN_QUERY, ctypes.byref(token)):
        raise RuntimeError("Failed to open process token")

    try:
        # Create environment block
        environment = ctypes.c_void_p()
        if not CreateEnvironmentBlock(ctypes.byref(environment), token, False):
            raise RuntimeError("Failed to create environment block")

        try:
            # Convert environment block to list of strings
            result = {}
            env_ptr = ctypes.cast(environment, ctypes.POINTER(ctypes.c_wchar))
            offset = 0

            while True:
                # Get string at current offset
                current_string = ""
                while env_ptr[offset] != "\0":
                    current_string += env_ptr[offset]
                    offset += 1

                # Skip null terminator
                offset += 1

                # Break if we hit double null terminator
                if not current_string:
                    break

                equal_index = current_string.index("=")
                if equal_index == -1:
                    continue

                key = current_string[:equal_index]
                value = current_string[equal_index + 1 :]
                result[key] = value

            return result

        finally:
            DestroyEnvironmentBlock(environment)

    finally:
        CloseHandle(token)


class FeedbackTextEdit(QTextEdit):
    def __init__(self, parent=None):
        super().__init__(parent)

    def keyPressEvent(self, event: QKeyEvent):
        if event.key() == Qt.Key_Return and event.modifiers() == Qt.ControlModifier:
            # Find the parent FeedbackUI instance and trigger submit click
            parent = self.parent()
            while parent and not isinstance(parent, FeedbackUI):
                parent = parent.parent()
            if parent:
                # Use _on_submit_clicked to respect multi-window confirmation
                parent._on_submit_clicked()
        else:
            super().keyPressEvent(event)

    def insertFromMimeData(self, source):
        # Override to strip formatting when pasting
        if source.hasText():
            # Insert only plain text, stripping all formatting
            plain_text = source.text()
            self.insertPlainText(plain_text)
        else:
            # For non-text data, use default behavior
            super().insertFromMimeData(source)


class LogSignals(QObject):
    append_log = Signal(str)


class FeedbackSignals(QObject):
    feedback_ready = Signal(dict)  # Emits FeedbackResult when window is done


class FeedbackUI(QMainWindow):
    def __init__(
        self,
        project_directory: str,
        prompt: str,
        task_id: str,
        timeout_seconds: int = 290,
    ):
        # Check if window with this task_id already exists
        if task_id in _OPEN_WINDOWS:
            raise ValueError(f"Window with task_id '{task_id}' already exists")

        super().__init__()
        self.project_directory = project_directory
        self.prompt = prompt
        self.timeout_seconds = timeout_seconds
        self.task_id = task_id

        # Register this window globally
        _OPEN_WINDOWS[task_id] = self

        self.process: Optional[subprocess.Popen] = None
        self.log_buffer: list[str] = []
        self.feedback_result: FeedbackResult | None = None
        self.log_signals = LogSignals()
        self.log_signals.append_log.connect(self._append_log)
        self.feedback_signals = FeedbackSignals()

        # Multi-window confirmation state
        self._pending_confirm = False  # Whether waiting for second click to confirm

        # Auto feedback timer
        self.auto_feedback_timer = QTimer()
        self.auto_feedback_timer.setSingleShot(True)
        self.auto_feedback_timer.timeout.connect(self._auto_submit_feedback)

        # Countdown display timer (updates every second)
        self.countdown_timer = QTimer()
        self.countdown_timer.timeout.connect(self._update_countdown_display)
        self.remaining_seconds = self.timeout_seconds

        # Set window title with project name for identification
        project_name = os.path.basename(os.path.normpath(self.project_directory))
        self.setWindowTitle(f"Interactive Feedback MCP - {project_name}")
        script_dir = os.path.dirname(os.path.abspath(__file__))
        icon_path = os.path.join(script_dir, "images", "feedback.png")
        self.setWindowIcon(QIcon(icon_path))
        self.setWindowFlags(self.windowFlags() | Qt.WindowStaysOnTopHint)

        self.settings = QSettings("InteractiveFeedbackMCP", "InteractiveFeedbackMCP")

        # Load general UI settings for the main window (geometry, state)
        self.settings.beginGroup("MainWindow_General")
        geometry = self.settings.value("geometry")
        if geometry:
            self.restoreGeometry(geometry)
        else:
            # Calculate offset position for multiple windows
            screen = QApplication.primaryScreen().geometry()
            base_x = (screen.width() - 800) // 2
            base_y = (screen.height() - 600) // 2

            # Count windows before this one to calculate offset
            window_count = len([w for w in _OPEN_WINDOWS.values() if w != self])
            offset = window_count * _WINDOW_OFFSET_STEP

            x = base_x + offset
            y = base_y + offset

            # Ensure window stays within screen bounds
            x = max(0, min(x, screen.width() - 800))
            y = max(0, min(y, screen.height() - 600))

            self.resize(800, 600)
            self.move(x, y)
        state = self.settings.value("windowState")
        if state:
            self.restoreState(state)
        self.settings.endGroup()  # End "MainWindow_General" group

        # Load task-specific settings (command, auto-execute, command section visibility, confirm before execute)
        # Use task_id for primary grouping, with project as fallback for compatibility
        self.task_group_name = f"Task_{self.task_id}"
        self.project_group_name = get_project_settings_group(self.project_directory)

        # Try task-specific settings first, fallback to project settings
        self.settings.beginGroup(self.task_group_name)
        loaded_run_command = self.settings.value("run_command", "", type=str)
        loaded_execute_auto = self.settings.value(
            "execute_automatically", False, type=bool
        )
        loaded_confirm_before_execute = self.settings.value(
            "confirm_before_execute", False, type=bool
        )
        loaded_workflow_mode = self.settings.value(
            "workflow_mode", "manual", type=str
        )
        loaded_review_scope = self.settings.value(
            "review_scope", "current_diff", type=str
        )
        loaded_auto_run_checks = self.settings.value(
            "auto_run_checks", False, type=bool
        )
        loaded_final_summary_to_docs = self.settings.value(
            "final_summary_to_docs", False, type=bool
        )
        command_section_visible = self.settings.value(
            "commandSectionVisible", False, type=bool
        )
        loaded_draft_input = self.settings.value("draft_input", "", type=str)
        self.settings.endGroup()

        # If no task-specific settings found, try project settings for backward compatibility
        if (
            not loaded_run_command
            and not loaded_execute_auto
            and not loaded_confirm_before_execute
            and not command_section_visible
        ):
            self.settings.beginGroup(self.project_group_name)
            loaded_run_command = self.settings.value("run_command", "", type=str)
            loaded_execute_auto = self.settings.value(
                "execute_automatically", False, type=bool
            )
            loaded_confirm_before_execute = self.settings.value(
                "confirm_before_execute", False, type=bool
            )
            loaded_workflow_mode = self.settings.value(
                "workflow_mode", loaded_workflow_mode, type=str
            )
            loaded_review_scope = self.settings.value(
                "review_scope", loaded_review_scope, type=str
            )
            loaded_auto_run_checks = self.settings.value(
                "auto_run_checks", loaded_auto_run_checks, type=bool
            )
            loaded_final_summary_to_docs = self.settings.value(
                "final_summary_to_docs", loaded_final_summary_to_docs, type=bool
            )
            command_section_visible = self.settings.value(
                "commandSectionVisible", False, type=bool
            )
            self.settings.endGroup()

        self.config: FeedbackConfig = {
            "run_command": loaded_run_command or "",
            "execute_automatically": loaded_execute_auto or False,
            "confirm_before_execute": loaded_confirm_before_execute or False,
            "workflow_mode": loaded_workflow_mode or "manual",
            "review_scope": loaded_review_scope or "current_diff",
            "auto_run_checks": loaded_auto_run_checks or False,
            "final_summary_to_docs": loaded_final_summary_to_docs or False,
        }

        self._create_ui()  # self.config is used here to set initial values

        # 恢复上次超时未提交的草稿
        if loaded_draft_input:
            self.feedback_text.setPlainText(loaded_draft_input)
            # 将光标移到末尾，方便继续输入
            cursor = self.feedback_text.textCursor()
            cursor.movePosition(QTextCursor.End)
            self.feedback_text.setTextCursor(cursor)

        # Command section is permanently hidden
        self.command_group.setVisible(False)

        set_dark_title_bar(self, True)

        if self.config.get("execute_automatically", False):
            self._run_command()

    def _update_countdown_display(self):
        """Update the countdown display every second"""
        self.remaining_seconds -= 1
        if self.remaining_seconds > 0:
            self.countdown_label.setText(f"⏰ {self.remaining_seconds}秒后即将重新询问")
        else:
            self.countdown_label.setText("⏰ 重新询问中...")
            self.countdown_timer.stop()

    def _adjust_description_height(self):
        """Adjust description label height based on content length"""
        if not hasattr(self, "description_label") or not self.description_label:
            return

        # Get text content
        text = self.description_label.toPlainText()
        if not text.strip():
            self.description_label.setFixedHeight(80)
            return

        # Calculate lines (rough estimation)
        font_metrics = self.description_label.fontMetrics()
        line_height = font_metrics.lineSpacing()

        # Use estimated width since actual width may not be available during initialization
        # Assume typical width for the widget area (accounting for margins and other UI elements)
        estimated_width = 700  # Rough estimate based on window width minus margins
        text_width = estimated_width - 40  # Account for padding and margins

        # Count actual lines by splitting and measuring
        lines = text.split("\n")
        total_lines = 0
        for line in lines:
            if not line.strip():
                total_lines += 1
            else:
                # Estimate wrapped lines
                line_width = font_metrics.horizontalAdvance(line)
                if line_width <= text_width:
                    total_lines += 1
                else:
                    wrapped_lines = (line_width // text_width) + 1
                    total_lines += wrapped_lines

        # Calculate target height with padding
        content_height = (
            total_lines * line_height + 24
        )  # Add padding for top/bottom margins
        target_height = min(200, max(80, content_height))

        self.description_label.setFixedHeight(target_height)

    def _get_selected_workflow_key(self) -> str:
        if not hasattr(self, "workflow_combo"):
            return self.config.get("workflow_mode", "manual")
        return self.workflow_combo.currentData() or "manual"

    def _get_selected_scope_key(self) -> str:
        if not hasattr(self, "review_scope_combo"):
            return self.config.get("review_scope", "current_diff")
        return self.review_scope_combo.currentData() or "current_diff"

    def _build_effective_prompt(self) -> str:
        user_input = self.feedback_text.toPlainText().strip()
        workflow_key = self._get_selected_workflow_key()
        scope_key = self._get_selected_scope_key()
        workflow = WORKFLOW_DEFINITIONS.get(
            workflow_key, WORKFLOW_DEFINITIONS["manual"]
        )
        scope = REVIEW_SCOPE_OPTIONS.get(scope_key, REVIEW_SCOPE_OPTIONS["current_diff"])

        if workflow_key == "manual":
            sections: list[str] = []
            if user_input:
                sections.append(user_input)
            if hasattr(self, "auto_run_checks_check") and self.auto_run_checks_check.isChecked():
                sections.append(
                    "【额外要求】完成本轮处理后，请主动运行合适的检查、测试或构建验证；如果当前项目没有明确测试入口，请至少说明你做了哪些验证。"
                )
            if (
                hasattr(self, "final_summary_to_docs_check")
                and self.final_summary_to_docs_check.isChecked()
            ):
                sections.append(
                    "【收尾要求】当本轮任务完成后，请额外把本次结果整理为项目文档：更新 docs/INDEX.md，并在 docs/ 目录下写入或更新一份本轮总结文档。完成后再重新调用 interactive_feedback。"
                )
            if hasattr(self, "confirm_before_execute_check") and self.confirm_before_execute_check.isChecked():
                sections.append(CONFIRMATION_INSTRUCTIONS.strip())
            sections.append(CONTINUOUS_DIALOGUE_SUFFIX.strip())
            return "\n\n".join(section.strip() for section in sections if section.strip())

        sections: list[str] = []
        if user_input:
            sections.append(user_input)

        sections.append(f"【当前工作流】{workflow['label']}")
        sections.append(f"【工作流目标】{workflow['description']}")
        sections.append(f"【执行要求】{workflow['instruction']}")

        if workflow.get("uses_scope"):
            sections.append(f"【处理范围】{scope['label']}：{scope['instruction']}")

        if hasattr(self, "auto_run_checks_check") and self.auto_run_checks_check.isChecked():
            sections.append(
                "【额外要求】完成修改后，请主动运行合适的检查、测试或构建验证；如果当前项目没有明确测试入口，请至少说明你做了哪些验证。"
            )

        if workflow_key in {"commit_only", "commit_push"}:
            sections.append(f"【提交规范】{COMMIT_MESSAGE_POLICY}")

        if (
            hasattr(self, "final_summary_to_docs_check")
            and self.final_summary_to_docs_check.isChecked()
        ):
            sections.append(
                "【收尾要求】当本轮任务完成后，请额外把本次结果整理为项目文档：更新 docs/INDEX.md，并在 docs/ 目录下写入或更新一份本轮总结文档。完成后再重新调用 interactive_feedback。"
            )

        if hasattr(self, "confirm_before_execute_check") and self.confirm_before_execute_check.isChecked():
            sections.append(CONFIRMATION_INSTRUCTIONS.strip())

        sections.append(CONTINUOUS_DIALOGUE_SUFFIX.strip())
        return "\n\n".join(section.strip() for section in sections if section.strip())

    def _toggle_workflow_group(self, checked: bool):
        if hasattr(self, "workflow_group"):
            self.workflow_group.setVisible(checked)
        if hasattr(self, "workflow_toggle_button"):
            self.workflow_toggle_button.setText(
                "🧭 工作流模式（点击收起）" if checked else "🧭 工作流模式（点击展开）"
            )
        if checked:
            self.adjustSize()
            current_size = self.size()
            target_height = min(max(current_size.height() + 220, 760), 1100)
            target_width = max(current_size.width(), 860)
            self.resize(target_width, target_height)
            if hasattr(self, "main_scroll_area"):
                QTimer.singleShot(
                    0,
                    lambda: self.main_scroll_area.verticalScrollBar().setValue(
                        self.main_scroll_area.verticalScrollBar().maximum()
                    ),
                )

    def _copy_preview_to_clipboard(self):
        if not hasattr(self, "workflow_preview"):
            return
        QApplication.clipboard().setText(self.workflow_preview.toPlainText())
        self._append_log("[信息] 已复制最终提示词预览到剪切板\n")

    def _show_full_prompt_preview(self):
        dialog = QDialog(self)
        dialog.setWindowTitle("最终提示词完整预览")
        dialog.resize(900, 700)

        layout = QVBoxLayout(dialog)
        layout.setContentsMargins(16, 16, 16, 16)
        layout.setSpacing(12)

        text = QPlainTextEdit()
        text.setReadOnly(True)
        text.setPlainText(self._build_effective_prompt())
        text.setStyleSheet(self.workflow_preview.styleSheet())
        layout.addWidget(text)

        button_row = QHBoxLayout()
        button_row.addStretch()

        copy_button = QPushButton("📋 复制")
        close_button = QPushButton("关闭")
        for btn in (copy_button, close_button):
            btn.setStyleSheet("""
                QPushButton {
                    background-color: #2a2a2a;
                    color: #e0e0e0;
                    border: 1px solid #404040;
                    border-radius: 6px;
                    padding: 8px 14px;
                    font-size: 12px;
                    font-weight: 500;
                }
                QPushButton:hover {
                    background-color: #333333;
                    border-color: #555555;
                }
            """)

        copy_button.clicked.connect(
            lambda: QApplication.clipboard().setText(text.toPlainText())
        )
        close_button.clicked.connect(dialog.accept)
        button_row.addWidget(copy_button)
        button_row.addWidget(close_button)
        layout.addLayout(button_row)

        dialog.exec()

    def _refresh_workflow_ui_state(self):
        workflow_key = self._get_selected_workflow_key()
        workflow = WORKFLOW_DEFINITIONS.get(
            workflow_key, WORKFLOW_DEFINITIONS["manual"]
        )

        if hasattr(self, "workflow_description_label"):
            self.workflow_description_label.setText(
                f"说明：{workflow['description']}"
            )

        uses_scope = bool(workflow.get("uses_scope"))
        supports_checks = bool(workflow.get("supports_checks"))

        if hasattr(self, "review_scope_label"):
            self.review_scope_label.setEnabled(uses_scope)
        if hasattr(self, "review_scope_combo"):
            self.review_scope_combo.setEnabled(uses_scope)
        if hasattr(self, "auto_run_checks_check"):
            self.auto_run_checks_check.setEnabled(supports_checks)

        if hasattr(self, "workflow_preview"):
            self.workflow_preview.setPlainText(self._build_effective_prompt())

    def _save_draft(self):
        """保存用户输入的草稿到 QSettings，以便下次窗口恢复"""
        user_input = self.feedback_text.toPlainText().strip()
        self.settings.beginGroup(self.task_group_name)
        if user_input:
            self.settings.setValue("draft_input", user_input)
        else:
            self.settings.remove("draft_input")
        self.settings.endGroup()

    def _clear_draft(self):
        """清除已保存的草稿"""
        self.settings.beginGroup(self.task_group_name)
        self.settings.remove("draft_input")
        self.settings.endGroup()

    def _auto_submit_feedback(self):
        """Auto submit feedback with default message after timeout"""
        user_input = self.feedback_text.toPlainText().strip()
        if user_input:
            # Backup user input to console log
            self._append_log(f"[备份] 用户输入内容: {user_input}\n")
            # Copy user input to system clipboard
            clipboard = QApplication.clipboard()
            clipboard.setText(user_input)
            self._append_log("[信息] 用户输入已复制到剪切板\n")
            # 保存草稿，下次打开窗口时恢复
            self._save_draft()
            self._append_log("[信息] 用户输入已保存为草稿，下次打开窗口时将自动恢复\n")
        # Always submit default feedback after timeout
        self.feedback_text.setPlainText(
            "好的，代码先保持现状，然后重新调用 interactive_feedback 工具，调用interactive_feedback后会有一个窗口，我将在窗口中告诉你下一步指令，请先调用interactive_feedback工具"
        )
        self._submit_feedback()

    def _format_windows_path(self, path: str) -> str:
        if sys.platform == "win32":
            # Convert forward slashes to backslashes
            path = path.replace("/", "\\")
            # Capitalize drive letter if path starts with x:\
            if len(path) >= 2 and path[1] == ":" and path[0].isalpha():
                path = path[0].upper() + path[1:]
        return path

    def _create_ui(self):
        outer_widget = QWidget()
        outer_widget.setStyleSheet("""
            QWidget {
                background-color: #121212;
            }
        """)
        outer_layout = QVBoxLayout(outer_widget)
        outer_layout.setContentsMargins(0, 0, 0, 0)
        outer_layout.setSpacing(0)

        self.main_scroll_area = QScrollArea()
        self.main_scroll_area.setWidgetResizable(True)
        self.main_scroll_area.setFrameShape(QScrollArea.Shape.NoFrame)
        self.main_scroll_area.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.main_scroll_area.setStyleSheet("""
            QScrollArea {
                border: none;
                background-color: #121212;
            }
            QScrollBar:vertical {
                background: #1a1a1a;
                width: 10px;
                margin: 0;
                border-radius: 5px;
            }
            QScrollBar::handle:vertical {
                background: #4a4a4a;
                min-height: 24px;
                border-radius: 5px;
            }
            QScrollBar::handle:vertical:hover {
                background: #5c5c5c;
            }
            QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical {
                height: 0px;
            }
        """)
        outer_layout.addWidget(self.main_scroll_area)
        self.setCentralWidget(outer_widget)

        central_widget = QWidget()
        self.main_scroll_area.setWidget(central_widget)

        checkbox_style = """
            QCheckBox {
                color: #a0a0a0;
                font-size: 12px;
                spacing: 8px;
            }
            QCheckBox::indicator {
                width: 16px;
                height: 16px;
                border: 1px solid #606060;
                border-radius: 3px;
                background-color: #252525;
            }
            QCheckBox::indicator:checked {
                background-color: #007bff;
                border: 1px solid #007bff;
            }
            QCheckBox::indicator:hover {
                border: 1px solid #007bff;
            }
        """

        # Set main background - elegant dark
        central_widget.setStyleSheet("""
            QWidget {
                background-color: #121212;
            }
        """)

        layout = QVBoxLayout(central_widget)
        layout.setSpacing(16)
        layout.setContentsMargins(20, 20, 20, 20)

        # Command section - Elegant dark design
        self.command_group = QGroupBox("🖥️ 命令控制台")
        self.command_group.setStyleSheet("""
            QGroupBox {
                font-size: 14px;
                font-weight: 600;
                border: 1px solid #404040;
                border-radius: 12px;
                margin-top: 8px;
                padding-top: 16px;
                background-color: #1e1e1e;
            }
            QGroupBox::title {
                color: #c0c0c0;
                font-size: 13px;
                font-weight: 600;
                padding: 2px 8px;
                margin-top: -10px;
                margin-left: 16px;
            }
        """)
        command_layout = QVBoxLayout(self.command_group)
        command_layout.setContentsMargins(20, 20, 20, 20)
        command_layout.setSpacing(12)

        # Working directory label - Simple dark style
        formatted_path = self._format_windows_path(self.project_directory)
        working_dir_label = QLabel(f"📁 工作目录: {formatted_path}")
        working_dir_label.setStyleSheet("""
            QLabel {
                color: #a0a0a0;
                font-size: 12px;
                padding: 8px 12px;
                background-color: #252525;
                border-radius: 6px;
            }
        """)
        command_layout.addWidget(working_dir_label)

        # Command input row - Clean dark design
        command_input_layout = QHBoxLayout()
        command_input_layout.setSpacing(12)

        self.command_entry = QLineEdit()
        self.command_entry.setText(self.config["run_command"])
        self.command_entry.setStyleSheet("""
            QLineEdit {
                background-color: #252525;
                color: #e0e0e0;
                border: 1px solid #404040;
                border-radius: 6px;
                padding: 10px 14px;
                font-size: 13px;
            }
            QLineEdit:focus {
                border: 1px solid #606060;
                background-color: #2a2a2a;
            }
            QLineEdit::placeholder {
                color: #808080;
            }
        """)
        self.command_entry.returnPressed.connect(self._run_command)
        self.command_entry.textChanged.connect(self._update_config)

        self.run_button = QPushButton("▶️ 运行")
        self.run_button.setStyleSheet("""
            QPushButton {
                background-color: #007bff;
                color: #ffffff;
                border: 1px solid #007bff;
                border-radius: 6px;
                padding: 10px 20px;
                font-size: 13px;
                font-weight: 500;
                min-width: 80px;
            }
            QPushButton:hover {
                background-color: #0056b3;
                border-color: #0056b3;
            }
            QPushButton:pressed {
                background-color: #004085;
            }
        """)
        self.run_button.clicked.connect(self._run_command)

        command_input_layout.addWidget(self.command_entry)
        command_input_layout.addWidget(self.run_button)
        command_layout.addLayout(command_input_layout)

        # Auto-execute and save config row - Simple dark style
        auto_layout = QHBoxLayout()
        auto_layout.setSpacing(12)

        self.auto_check = QCheckBox("🔄 下次运行时自动执行")
        self.auto_check.setStyleSheet(checkbox_style)

        save_button = QPushButton("💾 保存配置")
        save_button.setStyleSheet("""
            QPushButton {
                background-color: #28a745;
                color: #ffffff;
                border: 1px solid #28a745;
                border-radius: 6px;
                padding: 8px 16px;
                font-size: 12px;
                font-weight: 500;
            }
            QPushButton:hover {
                background-color: #218838;
                border-color: #218838;
            }
            QPushButton:pressed {
                background-color: #1e7e34;
            }
        """)
        save_button.clicked.connect(self._save_config)

        auto_layout.addWidget(self.auto_check)
        auto_layout.addStretch()
        auto_layout.addWidget(save_button)
        command_layout.addLayout(auto_layout)

        # Console section (now part of command_group) - Dark terminal style
        console_group = QGroupBox("📜 控制台输出")
        console_group.setStyleSheet("""
            QGroupBox {
                font-size: 14px;
                font-weight: 600;
                border: 1px solid #404040;
                border-radius: 8px;
                margin-top: 8px;
                padding-top: 16px;
                background-color: #1e1e1e;
            }
            QGroupBox::title {
                color: #c0c0c0;
                font-size: 13px;
                font-weight: 600;
                padding: 2px 8px;
                margin-top: -10px;
                margin-left: 16px;
            }
        """)
        console_group.setMinimumHeight(200)
        console_layout_internal = QVBoxLayout(console_group)
        console_layout_internal.setContentsMargins(16, 16, 16, 16)

        # Log text area - Light terminal style
        self.log_text = QTextEdit()
        self.log_text.setReadOnly(True)
        font = QFont(QFontDatabase.systemFont(QFontDatabase.FixedFont))
        font.setPointSize(10)
        self.log_text.setFont(font)
        self.log_text.setStyleSheet("""
            QTextEdit {
                background-color: #0a0a0a;
                color: #c0c0c0;
                border: 1px solid #333333;
                border-radius: 4px;
                padding: 8px;
                font-family: monospace;
                selection-background-color: #404040;
            }
        """)
        console_layout_internal.addWidget(self.log_text)

        # Clear button - Simple dark style
        button_layout = QHBoxLayout()
        button_layout.setContentsMargins(0, 8, 0, 0)

        self.clear_button = QPushButton("🗑️ 清空控制台")
        self.clear_button.setStyleSheet("""
            QPushButton {
                background-color: #dc3545;
                color: #ffffff;
                border: 1px solid #dc3545;
                border-radius: 4px;
                padding: 6px 12px;
                font-size: 12px;
                font-weight: 500;
            }
            QPushButton:hover {
                background-color: #c82333;
                border-color: #c82333;
            }
            QPushButton:pressed {
                background-color: #bd2130;
            }
        """)
        self.clear_button.clicked.connect(self.clear_logs)
        button_layout.addStretch()
        button_layout.addWidget(self.clear_button)
        console_layout_internal.addLayout(button_layout)

        command_layout.addWidget(console_group)

        self.command_group.setVisible(False)
        layout.addWidget(self.command_group)

        # Feedback section - Light design
        self.feedback_group = QGroupBox("💬 用户反馈")
        self.feedback_group.setStyleSheet("""
            QGroupBox {
                font-size: 16px;
                font-weight: 700;
                border: 2px solid #404040;
                border-radius: 12px;
                margin-top: 8px;
                padding-top: 20px;
                background-color: #1a1a1a;
            }
            QGroupBox::title {
                color: #e0e0e0;
                font-size: 14px;
                font-weight: 700;
                padding: 2px 8px;
                margin-top: -12px;
                margin-left: 20px;
            }
        """)
        feedback_layout = QVBoxLayout(self.feedback_group)
        feedback_layout.setContentsMargins(24, 24, 24, 24)
        feedback_layout.setSpacing(16)

        # Header section - Compact layout
        header_layout = QHBoxLayout()

        # Project identification label - Compact style
        project_path = os.path.abspath(self.project_directory)
        project_name = os.path.basename(project_path)
        # 如果是当前目录且basename返回"."，则使用绝对路径的basename
        if project_name == "." or project_name == "":
            project_name = os.path.basename(os.path.dirname(project_path))
        project_path_label = QLabel(f"🎯 {project_name}")
        project_path_label.setStyleSheet("""
            QLabel {
                color: #e0e0e0;
                font-size: 14px;
                font-weight: 600;
                padding: 4px 8px;
                background-color: #404040;
                border-radius: 4px;
            }
        """)
        header_layout.addWidget(project_path_label)

        # Task ID label - Only show if task_id is provided
        if self.task_id:
            task_id_label = QLabel(f"📋 {self.task_id}")
            task_id_label.setStyleSheet("""
                QLabel {
                    color: #a0d8ff;
                    font-size: 12px;
                    font-weight: 500;
                    padding: 4px 8px;
                    background-color: #2a4a6b;
                    border-radius: 4px;
                }
            """)
            header_layout.addWidget(task_id_label)

        header_layout.addStretch()

        # Countdown display label - Compact style
        self.countdown_label = QLabel(f"⏰ {self.timeout_seconds}秒")
        self.countdown_label.setStyleSheet("""
            QLabel {
                color: #ff6b6b;
                font-size: 12px;
                padding: 4px 8px;
                background-color: #404040;
                border-radius: 4px;
            }
        """)
        header_layout.addWidget(self.countdown_label)

        feedback_layout.addLayout(header_layout)

        # Short description text edit - Simple styling
        self.description_label = QPlainTextEdit(self.prompt)
        self.description_label.setReadOnly(True)
        # Set fixed height for short content, expandable for longer content
        self._adjust_description_height()
        self.description_label.setStyleSheet("""
            QPlainTextEdit {
                color: #c0c0c0;
                font-size: 13px;
                line-height: 1.4;
                padding: 8px 12px;
                background-color: #404040;
                border-radius: 6px;
                border: none;
                selection-background-color: #606060;
            }
            QPlainTextEdit:focus {
                border: 1px solid #606060;
            }
        """)
        feedback_layout.addWidget(self.description_label)

        # Feedback text input - Clean dark design with more space
        self.feedback_text = FeedbackTextEdit()
        font_metrics = self.feedback_text.fontMetrics()
        row_height = font_metrics.height()
        # Calculate height for 3 lines to give compact input area
        padding = (
            self.feedback_text.contentsMargins().top()
            + self.feedback_text.contentsMargins().bottom()
            + 10
        )
        self.feedback_text.setMinimumHeight(3 * row_height + padding)
        self.feedback_text.setStyleSheet("""
            QTextEdit {
                background-color: #252525;
                color: #e0e0e0;
                border: 1px solid #404040;
                border-radius: 8px;
                padding: 12px;
                font-size: 14px;
                line-height: 1.6;
                selection-background-color: #404040;
            }
            QTextEdit:focus {
                border: 1px solid #606060;
                background-color: #2a2a2a;
            }
            QTextEdit::placeholder {
                color: #808080;
                font-style: italic;
            }
        """)

        self.feedback_text.setPlaceholderText(
            "请在此输入您的反馈和指示... (按 Ctrl+Enter 发送)"
        )
        self.feedback_text.textChanged.connect(self._refresh_workflow_ui_state)

        # Workflow launcher section
        self.workflow_toggle_button = QPushButton("🧭 工作流模式（点击展开）")
        self.workflow_toggle_button.setCheckable(True)
        self.workflow_toggle_button.setChecked(False)
        self.workflow_toggle_button.setStyleSheet("""
            QPushButton {
                background-color: #202020;
                color: #d0d0d0;
                border: 1px solid #404040;
                border-radius: 8px;
                padding: 10px 14px;
                font-size: 13px;
                font-weight: 600;
                text-align: left;
            }
            QPushButton:hover {
                background-color: #2a2a2a;
                border-color: #606060;
            }
            QPushButton:checked {
                background-color: #2a3644;
                border-color: #4b6a86;
            }
        """)
        feedback_layout.addWidget(self.workflow_toggle_button)

        workflow_group = QGroupBox("🧭 工作流模式")
        workflow_group.setStyleSheet(self.feedback_group.styleSheet())
        workflow_layout = QVBoxLayout(workflow_group)
        workflow_layout.setContentsMargins(20, 20, 20, 20)
        workflow_layout.setSpacing(12)

        workflow_row = QHBoxLayout()
        workflow_row.setSpacing(12)

        workflow_label = QLabel("模式：")
        workflow_label.setStyleSheet("color: #c0c0c0; font-size: 13px; font-weight: 600;")
        workflow_row.addWidget(workflow_label)

        self.workflow_combo = QComboBox()
        self.workflow_combo.setStyleSheet("""
            QComboBox {
                background-color: #252525;
                color: #e0e0e0;
                border: 1px solid #404040;
                border-radius: 6px;
                padding: 8px 12px;
                font-size: 13px;
                min-width: 230px;
            }
            QComboBox::drop-down {
                border: none;
                width: 24px;
            }
            QComboBox QAbstractItemView {
                background-color: #1f1f1f;
                color: #e0e0e0;
                border: 1px solid #404040;
                selection-background-color: #2a4a6b;
            }
        """)
        for key, workflow in WORKFLOW_DEFINITIONS.items():
            self.workflow_combo.addItem(workflow["label"], key)
        workflow_index = self.workflow_combo.findData(self.config.get("workflow_mode", "manual"))
        if workflow_index >= 0:
            self.workflow_combo.setCurrentIndex(workflow_index)
        workflow_row.addWidget(self.workflow_combo)

        self.review_scope_label = QLabel("范围：")
        self.review_scope_label.setStyleSheet(
            "color: #c0c0c0; font-size: 13px; font-weight: 600;"
        )
        workflow_row.addWidget(self.review_scope_label)

        self.review_scope_combo = QComboBox()
        self.review_scope_combo.setStyleSheet(self.workflow_combo.styleSheet())
        for key, scope in REVIEW_SCOPE_OPTIONS.items():
            self.review_scope_combo.addItem(scope["label"], key)
        scope_index = self.review_scope_combo.findData(
            self.config.get("review_scope", "current_diff")
        )
        if scope_index >= 0:
            self.review_scope_combo.setCurrentIndex(scope_index)
        workflow_row.addWidget(self.review_scope_combo)
        workflow_row.addStretch()
        workflow_layout.addLayout(workflow_row)

        self.workflow_description_label = QLabel()
        self.workflow_description_label.setWordWrap(True)
        self.workflow_description_label.setStyleSheet(
            "color: #9fb7c9; font-size: 12px; line-height: 1.4;"
        )
        workflow_layout.addWidget(self.workflow_description_label)

        options_row = QHBoxLayout()
        options_row.setSpacing(16)

        self.auto_run_checks_check = QCheckBox("自动运行检查/测试")
        self.final_summary_to_docs_check = QCheckBox("完成后补充 docs 总结")
        for checkbox in (
            self.auto_run_checks_check,
            self.final_summary_to_docs_check,
        ):
            checkbox.setStyleSheet(checkbox_style)
            options_row.addWidget(checkbox)

        options_row.addStretch()
        workflow_layout.addLayout(options_row)

        self.auto_run_checks_check.setChecked(self.config.get("auto_run_checks", False))
        self.final_summary_to_docs_check.setChecked(
            self.config.get("final_summary_to_docs", False)
        )

        preview_label = QLabel("预览：将发送给模型的最终提示词")
        preview_label.setStyleSheet(
            "color: #c0c0c0; font-size: 12px; font-weight: 600;"
        )
        workflow_layout.addWidget(preview_label)

        self.workflow_preview = QPlainTextEdit()
        self.workflow_preview.setReadOnly(True)
        self.workflow_preview.setMinimumHeight(170)
        self.workflow_preview.setStyleSheet("""
            QPlainTextEdit {
                color: #cfd8dc;
                font-size: 12px;
                line-height: 1.5;
                padding: 10px 12px;
                background-color: #202020;
                border-radius: 6px;
                border: 1px solid #404040;
                selection-background-color: #606060;
            }
        """)
        workflow_layout.addWidget(self.workflow_preview)

        preview_button_row = QHBoxLayout()
        preview_button_row.addStretch()

        self.copy_preview_button = QPushButton("📋 复制预览")
        self.expand_preview_button = QPushButton("🔎 查看完整预览")
        for btn in (self.copy_preview_button, self.expand_preview_button):
            btn.setStyleSheet("""
                QPushButton {
                    background-color: #2a2a2a;
                    color: #e0e0e0;
                    border: 1px solid #404040;
                    border-radius: 6px;
                    padding: 8px 12px;
                    font-size: 12px;
                    font-weight: 500;
                }
                QPushButton:hover {
                    background-color: #333333;
                    border-color: #555555;
                }
            """)
            preview_button_row.addWidget(btn)

        workflow_layout.addLayout(preview_button_row)

        self.workflow_group = workflow_group
        self.workflow_group.setVisible(False)
        feedback_layout.addWidget(self.workflow_group)

        self.workflow_combo.currentIndexChanged.connect(self._update_config)
        self.workflow_combo.currentIndexChanged.connect(self._refresh_workflow_ui_state)
        self.review_scope_combo.currentIndexChanged.connect(self._update_config)
        self.review_scope_combo.currentIndexChanged.connect(self._refresh_workflow_ui_state)
        self.auto_run_checks_check.stateChanged.connect(self._update_config)
        self.auto_run_checks_check.stateChanged.connect(self._refresh_workflow_ui_state)
        self.final_summary_to_docs_check.stateChanged.connect(self._update_config)
        self.final_summary_to_docs_check.stateChanged.connect(self._refresh_workflow_ui_state)
        self.workflow_toggle_button.toggled.connect(self._toggle_workflow_group)
        self.copy_preview_button.clicked.connect(self._copy_preview_to_clipboard)
        self.expand_preview_button.clicked.connect(self._show_full_prompt_preview)

        # Submit button - Clean dark style
        self.submit_button = QPushButton("🚀 发送反馈 (Ctrl+Enter)")
        self._submit_button_default_style = """
            QPushButton {
                background-color: #2a2a2a;
                color: #e0e0e0;
                border: 1px solid #404040;
                border-radius: 8px;
                padding: 12px 20px;
                font-size: 14px;
                font-weight: 600;
                min-height: 20px;
            }
            QPushButton:hover {
                background-color: #333333;
                border-color: #555555;
            }
            QPushButton:pressed {
                background-color: #1a1a1a;
            }
            QPushButton:focus {
                border: 1px solid #606060;
            }
        """
        self._submit_button_confirm_style = """
            QPushButton {
                background-color: #28a745;
                color: #ffffff;
                border: 2px solid #28a745;
                border-radius: 8px;
                padding: 12px 20px;
                font-size: 14px;
                font-weight: 700;
                min-height: 20px;
            }
            QPushButton:hover {
                background-color: #218838;
                border-color: #218838;
            }
            QPushButton:pressed {
                background-color: #1e7e34;
            }
            QPushButton:focus {
                border: 2px solid #1e7e34;
            }
        """
        self.submit_button.setStyleSheet(self._submit_button_default_style)
        self.submit_button.clicked.connect(self._on_submit_clicked)

        # Pause button - returns control to the LLM asking it to clarify via ask_question
        self.pause_button = QPushButton("⏸️ 暂停")
        self.pause_button.setStyleSheet("""
            QPushButton {
                background-color: #2a2a2a;
                color: #e0a030;
                border: 1px solid #6a5020;
                border-radius: 8px;
                padding: 12px 16px;
                font-size: 14px;
                font-weight: 600;
                min-height: 20px;
            }
            QPushButton:hover {
                background-color: #333333;
                border-color: #e0a030;
            }
            QPushButton:pressed {
                background-color: #1a1a1a;
            }
        """)
        self.pause_button.setToolTip(
            "忽略输入框内容，直接让大模型调用一次 ask_question 确认需求后再执行"
        )
        self.pause_button.clicked.connect(self._pause_and_confirm)

        # End button - asks the LLM to summarize the session into docs/ and stop
        self.end_button = QPushButton("🏁 结束")
        self.end_button.setStyleSheet("""
            QPushButton {
                background-color: #2a2a2a;
                color: #e05050;
                border: 1px solid #6a2020;
                border-radius: 8px;
                padding: 12px 16px;
                font-size: 14px;
                font-weight: 600;
                min-height: 20px;
            }
            QPushButton:hover {
                background-color: #333333;
                border-color: #e05050;
            }
            QPushButton:pressed {
                background-color: #1a1a1a;
            }
        """)
        self.end_button.setToolTip(
            "忽略输入框内容，让大模型把本次会话总结写入项目 docs/ 目录后直接结束会话"
        )
        self.end_button.clicked.connect(self._end_session)

        # Confirmation checkbox - Clean dark style
        self.confirm_before_execute_check = QCheckBox("🔍 需要先确认方案后再执行")
        self.confirm_before_execute_check.setStyleSheet(checkbox_style)

        submit_row_layout = QHBoxLayout()
        submit_row_layout.setSpacing(8)
        submit_row_layout.addWidget(self.submit_button, 3)
        submit_row_layout.addWidget(self.pause_button, 1)
        submit_row_layout.addWidget(self.end_button, 1)

        feedback_layout.addWidget(self.feedback_text)
        feedback_layout.addWidget(self.confirm_before_execute_check)
        feedback_layout.addLayout(submit_row_layout)

        # Set minimum height for feedback_group to accommodate its contents
        # This will be based on the description label and the expanded feedback_text
        self.feedback_group.setMinimumHeight(
            self.description_label.sizeHint().height()
            + self.feedback_text.minimumHeight()
            + self.submit_button.sizeHint().height()
            + feedback_layout.spacing() * 3  # More spacing for header layout
            + feedback_layout.contentsMargins().top()
            + feedback_layout.contentsMargins().bottom()
            + 10
        )  # 10 for extra padding

        # Add widgets in a specific order
        layout.addWidget(self.feedback_group)

        self.command_group.setVisible(False)

        # Set initial states for checkboxes after all UI elements are created
        self.auto_check.setChecked(self.config.get("execute_automatically", False))
        self.confirm_before_execute_check.setChecked(
            self.config.get("confirm_before_execute", False)
        )
        self.auto_check.stateChanged.connect(self._update_config)
        self.confirm_before_execute_check.stateChanged.connect(self._update_config)
        self.confirm_before_execute_check.stateChanged.connect(
            self._refresh_workflow_ui_state
        )
        self._refresh_workflow_ui_state()

    def _update_config(self):
        self.config["run_command"] = self.command_entry.text()
        self.config["execute_automatically"] = self.auto_check.isChecked()
        self.config["confirm_before_execute"] = (
            self.confirm_before_execute_check.isChecked()
        )
        if hasattr(self, "workflow_combo"):
            self.config["workflow_mode"] = self._get_selected_workflow_key()
        if hasattr(self, "review_scope_combo"):
            self.config["review_scope"] = self._get_selected_scope_key()
        if hasattr(self, "auto_run_checks_check"):
            self.config["auto_run_checks"] = self.auto_run_checks_check.isChecked()
        if hasattr(self, "final_summary_to_docs_check"):
            self.config["final_summary_to_docs"] = (
                self.final_summary_to_docs_check.isChecked()
            )

    def _append_log(self, text: str):
        self.log_buffer.append(text)
        self.log_text.append(text.rstrip())
        cursor = self.log_text.textCursor()
        cursor.movePosition(QTextCursor.End)
        self.log_text.setTextCursor(cursor)

    def _check_process_status(self):
        if self.process and self.process.poll() is not None:
            # Process has terminated
            exit_code = self.process.poll()
            self._append_log(f"\nProcess exited with code {exit_code}\n")
            self.run_button.setText("&Run")
            self.process = None
            self.activateWindow()
            self.feedback_text.setFocus()

    def _run_command(self):
        if self.process:
            kill_tree(self.process)
            self.process = None
            self.run_button.setText("&Run")
            return

        # Clear the log buffer but keep UI logs visible
        self.log_buffer = []

        command = self.command_entry.text()
        if not command:
            self._append_log("请输入要运行的命令\n")
            return

        self._append_log(f"$ {command}\n")
        self.run_button.setText("Sto&p")

        try:
            self.process = subprocess.Popen(
                command,
                shell=True,
                cwd=self.project_directory,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                env=get_user_environment(),
                text=True,
                bufsize=1,
                encoding="utf-8",
                errors="ignore",
                close_fds=True,
            )

            def read_output(pipe):
                for line in iter(pipe.readline, ""):
                    self.log_signals.append_log.emit(line)

            threading.Thread(
                target=read_output, args=(self.process.stdout,), daemon=True
            ).start()

            threading.Thread(
                target=read_output, args=(self.process.stderr,), daemon=True
            ).start()

            # Start process status checking
            self.status_timer = QTimer()
            self.status_timer.timeout.connect(self._check_process_status)
            self.status_timer.start(100)  # Check every 100ms

        except Exception as e:
            self._append_log(f"Error running command: {str(e)}\n")
            self.run_button.setText("&Run")

    def _get_project_display_name(self) -> str:
        """Get a short display name for the project"""
        project_path = os.path.abspath(self.project_directory)
        project_name = os.path.basename(project_path)
        if project_name == "." or project_name == "":
            project_name = os.path.basename(os.path.dirname(project_path))
        return project_name

    def _has_multiple_windows(self) -> bool:
        """Check if there are multiple feedback windows open"""
        return len(_OPEN_WINDOWS) > 1

    def _on_submit_clicked(self):
        """Handle submit button click with multi-window confirmation"""
        if self._has_multiple_windows() and not self._pending_confirm:
            # First click: enter confirmation mode
            self._enter_confirm_mode()
        else:
            # Single window or already confirmed: submit directly
            self._submit_feedback()

    def _enter_confirm_mode(self):
        """Enter confirmation mode - change button to show project/task info"""
        self._pending_confirm = True
        project_name = self._get_project_display_name()
        task_display = self.task_id if self.task_id else "未知任务"

        # Update button text and style
        self.submit_button.setText(f"✅ 确认发送到 [{project_name} - {task_display}]")
        self.submit_button.setStyleSheet(self._submit_button_confirm_style)

        # Set a timer to reset confirmation state after 5 seconds if no action
        self._confirm_reset_timer = QTimer()
        self._confirm_reset_timer.setSingleShot(True)
        self._confirm_reset_timer.timeout.connect(self._reset_confirm_mode)
        self._confirm_reset_timer.start(5000)  # 5 seconds to confirm

    def _reset_confirm_mode(self):
        """Reset from confirmation mode back to normal"""
        self._pending_confirm = False
        self.submit_button.setText("🚀 发送反馈 (Ctrl+Enter)")
        self.submit_button.setStyleSheet(self._submit_button_default_style)
        if (
            hasattr(self, "_confirm_reset_timer")
            and self._confirm_reset_timer.isActive()
        ):
            self._confirm_reset_timer.stop()

    def _submit_feedback(self):
        # Reset confirmation mode if active
        if self._pending_confirm:
            self._reset_confirm_mode()

        # Stop both timers when submitting
        if self.auto_feedback_timer.isActive():
            self.auto_feedback_timer.stop()
        if self.countdown_timer.isActive():
            self.countdown_timer.stop()

        # 用户正常提交，清除草稿
        self._clear_draft()

        final_prompt = self._build_effective_prompt()
        self.feedback_result = FeedbackResult(interactive_feedback=final_prompt)

        # Emit signal before closing
        self.feedback_signals.feedback_ready.emit(self.feedback_result)

        self.close()

    def _pause_and_confirm(self):
        """Ignore any text in the input box and immediately hand control back to
        the LLM, instructing it to call ask_question once before proceeding."""
        # Reset confirmation mode if active
        if self._pending_confirm:
            self._reset_confirm_mode()

        # Stop both timers when submitting
        if self.auto_feedback_timer.isActive():
            self.auto_feedback_timer.stop()
        if self.countdown_timer.isActive():
            self.countdown_timer.stop()

        # 忽略输入框内容，不保存/清除草稿
        self.feedback_result = FeedbackResult(interactive_feedback=PAUSE_INSTRUCTIONS)

        # Emit signal before closing
        self.feedback_signals.feedback_ready.emit(self.feedback_result)

        self.close()

    def _end_session(self):
        """Ignore any text in the input box and tell the LLM to summarize this
        session into project docs/ and stop calling interactive_feedback."""
        # Reset confirmation mode if active
        if self._pending_confirm:
            self._reset_confirm_mode()

        # Stop both timers when submitting
        if self.auto_feedback_timer.isActive():
            self.auto_feedback_timer.stop()
        if self.countdown_timer.isActive():
            self.countdown_timer.stop()

        # 用户主动结束会话，清除草稿
        self._clear_draft()

        # 忽略输入框内容
        self.feedback_result = FeedbackResult(
            interactive_feedback=END_SESSION_INSTRUCTIONS
        )

        # Emit signal before closing
        self.feedback_signals.feedback_ready.emit(self.feedback_result)

        self.close()

    def clear_logs(self):
        self.log_buffer = []
        self.log_text.clear()

    def _save_config(self):
        # Save run_command, execute_automatically, and confirm_before_execute to QSettings under task group
        self.settings.beginGroup(self.task_group_name)
        self.settings.setValue("run_command", self.config["run_command"])
        self.settings.setValue(
            "execute_automatically", self.config["execute_automatically"]
        )
        self.settings.setValue(
            "confirm_before_execute", self.config["confirm_before_execute"]
        )
        self.settings.setValue("workflow_mode", self.config["workflow_mode"])
        self.settings.setValue("review_scope", self.config["review_scope"])
        self.settings.setValue("auto_run_checks", self.config["auto_run_checks"])
        self.settings.setValue(
            "final_summary_to_docs", self.config["final_summary_to_docs"]
        )
        self.settings.endGroup()
        self._append_log(f"Configuration saved for task '{self.task_id}'.\n")

    def closeEvent(self, event):
        # Stop both timers when closing
        if self.auto_feedback_timer.isActive():
            self.auto_feedback_timer.stop()
        if self.countdown_timer.isActive():
            self.countdown_timer.stop()

        # 当用户主动关闭窗口时，设置反馈结果为"会话可以结束了"
        if not self.feedback_result:
            self.feedback_result = FeedbackResult(interactive_feedback="请结束会话！")

        # Emit signal when window is closed (if not already emitted)
        if self.feedback_result:
            self.feedback_signals.feedback_ready.emit(self.feedback_result)

        # Save general UI settings for the main window (geometry, state)
        self.settings.beginGroup("MainWindow_General")
        self.settings.setValue("geometry", self.saveGeometry())
        self.settings.setValue("windowState", self.saveState())
        self.settings.endGroup()

        # Save task-specific command section visibility (this is now slightly redundant due to immediate save in toggle, but harmless)
        self.settings.beginGroup(self.task_group_name)
        self.settings.setValue("commandSectionVisible", self.command_group.isVisible())
        self.settings.endGroup()

        # Remove this window from global tracking
        if self.task_id in _OPEN_WINDOWS:
            del _OPEN_WINDOWS[self.task_id]

        if self.process:
            kill_tree(self.process)
        super().closeEvent(event)

    def run(self) -> None:
        """Show the window and start timers. Results are emitted via signals."""
        self.show()
        # Adjust description height after window is shown and has proper dimensions
        QTimer.singleShot(100, self._adjust_description_height)
        # Start both timers after showing the window
        self.auto_feedback_timer.start(
            self.timeout_seconds * 1000
        )  # Convert to milliseconds
        self.countdown_timer.start(1000)  # Update every second


def get_project_settings_group(project_dir: str) -> str:
    # Create a safe, unique group name from the project directory path
    # Using only the last component + hash of full path to keep it somewhat readable but unique
    basename = os.path.basename(os.path.normpath(project_dir))
    full_hash = hashlib.md5(project_dir.encode("utf-8")).hexdigest()[:8]
    return f"{basename}_{full_hash}"


def feedback_ui(
    project_directory: str,
    prompt: str,
    task_id: str,
    output_file: Optional[str] = None,
    timeout_seconds: int = 290,
) -> tuple[Optional[FeedbackResult], str]:
    app = QApplication.instance() or QApplication()
    app.setPalette(get_dark_mode_palette(app))
    app.setStyle("Fusion")

    result = None

    def on_feedback_ready(feedback_result):
        nonlocal result
        result = feedback_result

        if output_file:
            # Ensure the directory exists
            os.makedirs(
                os.path.dirname(output_file) if os.path.dirname(output_file) else ".",
                exist_ok=True,
            )
            # Save the result to the output file
            with open(output_file, "w") as f:
                json.dump(result, f)

        # Quit the application when result is ready
        app.quit()

    ui = FeedbackUI(project_directory, prompt, task_id, timeout_seconds)
    ui.feedback_signals.feedback_ready.connect(on_feedback_ready)
    ui.run()

    # Run the event loop - this is required for Qt to work
    app.exec()

    logs = "".join(ui.log_buffer)
    return result, logs


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Run the feedback UI")
    parser.add_argument(
        "--project-directory",
        default=os.getcwd(),
        help="The project directory to run the command in",
    )
    parser.add_argument(
        "--prompt",
        default="I implemented the changes you requested.",
        help="The prompt to show to the user",
    )
    parser.add_argument(
        "--output-file", help="Path to save the feedback result as JSON"
    )
    parser.add_argument(
        "--timeout-seconds",
        type=int,
        default=290,
        help="Timeout in seconds for auto-feedback (default: 290)",
    )
    parser.add_argument(
        "--task-id",
        required=True,
        help="Task identifier to distinguish different tasks (required)",
    )
    args = parser.parse_args()

    result, logs = feedback_ui(
        args.project_directory,
        args.prompt,
        args.task_id,
        args.output_file,
        args.timeout_seconds,
    )
    if logs:
        print(f"\nLogs collected: \n{logs}")
    if result:
        print(f"\nFeedback received:\n{result['interactive_feedback']}")
    sys.exit(0)
